### ISSUE TITLE
Support cursors?

### ISSUE THREAD

**Issue by phated** [iceddev/omniscient-dom#1]
Should this support cursors?  If so, what would be the best way?

**Comment by mikaelbr** [comment]
My initial thought is that this might be too "context based" for a end user to understand. It would be cool for a DOM-component to be able to take a cursor that's pointing to a number, string, bool, etc. But what would happen if it points to an Immutable Map, Set, List, Seq, etc? Should any input that _is_ a cursor, but `.deref()` points to an immutable structure show a warning, and show empty result? Or should it create children in some way? Or should it stringify it?

I can't think a "perfect" solution, right now, but maybe there is a solution that could work - or maybe not :thought_balloon:

**Comment by mikaelbr** [comment]
For discussion: #2

**Comment by phated** [comment]
I like the solution from #2.  Merged
